# Generated by Django 4.2.7 on 2023-12-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('author', 'Author')], default='customer', max_length=50)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('account_creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
